### ISSUE TITLE
It should be possible to improve on the documentation

### ISSUE THREAD

**Issue by kimb** [jdave/JDave#10]
Please release at least the core content of http://jdave.org/ with some kind of (hopefully permissive) licencing.

**Comment by anpieber** [comment]
best would be if the documentation could also be a git repo we can provide pull requests for

**Comment by mpeltonen** [comment]
jdave.org source is already here: https://github.com/jdave/jdave.github.com

I think you should be able to access it, no?

**Comment by anpieber** [comment]
oh, great, I've missed that; thx. So I think the issue can be closed?

**Comment by mpeltonen** [comment]
Yeah, closing...
